
AllCops:
  Exclude:
    - 'lib/sparkql_v2/parser.rb'
    - 'vendor/**/*'
    - '.git/**/*'

Style/SymbolArray:
    EnforcedStyle: brackets

Style/WordArray:
    EnforcedStyle: brackets

Metrics/LineLength:
    Max: 90
    Exclude:
      - 'test/**/*'

Metrics/ClassLength:
    Exclude:
      - 'test/**/*'
